%% Initialize
parainfluenzaCombined = parainfluenza_init;

%% Position by frame
parainfluenzaCombined.set1.prePosition = ...
    cellfun(@(x) parainfluenza_position(x), ...
    parainfluenzaCombined.set1.prePath, 'uni', 0);
parainfluenzaCombined.set1.postPosition = ...
    cellfun(@(x) parainfluenza_position(x), ...
    parainfluenzaCombined.set1.postPath, 'uni', 0);
parainfluenzaCombined.set2.prePosition = ...
    cellfun(@(x) parainfluenza_position(x), ...
    parainfluenzaCombined.set2.prePath, 'uni', 0);
parainfluenzaCombined.set2.postPosition = ...
    cellfun(@(x) parainfluenza_position(x), ...
    parainfluenzaCombined.set2.postPath, 'uni', 0);

%% Periphery by frame
parainfluenzaCombined.set1.prePeripheral = ...
    cellfun(@(x, y) parainfluenza_periphery(x, y), ...
    parainfluenzaCombined.set1.prePosition, ...
    parainfluenzaCombined.set1.prePerim, 'uni', 0);
parainfluenzaCombined.set1.postPeripheral = ...
    cellfun(@(x, y) parainfluenza_periphery(x, y), ...
    parainfluenzaCombined.set1.postPosition, ...
    parainfluenzaCombined.set1.postPerim, 'uni', 0);
parainfluenzaCombined.set2.prePeripheral = ...
    cellfun(@(x, y) parainfluenza_periphery(x, y), ...
    parainfluenzaCombined.set2.prePosition, ...
    parainfluenzaCombined.set2.prePerim, 'uni', 0);
parainfluenzaCombined.set2.postPeripheral = ...
    cellfun(@(x, y) parainfluenza_periphery(x, y), ...
    parainfluenzaCombined.set2.postPosition, ...
    parainfluenzaCombined.set2.postPerim, 'uni', 0);

%% Velocity by frame
parainfluenzaCombined.set1.preVelocity = ...
    cellfun(@(x) parainfluenza_velocity(x), ...
    parainfluenzaCombined.set1.prePath, 'uni', 0);
parainfluenzaCombined.set1.postVelocity = ...
    cellfun(@(x) parainfluenza_velocity(x), ...
    parainfluenzaCombined.set1.postPath, 'uni', 0);
parainfluenzaCombined.set2.preVelocity = ...
    cellfun(@(x) parainfluenza_velocity(x), ...
    parainfluenzaCombined.set2.prePath, 'uni', 0);
parainfluenzaCombined.set2.postVelocity = ...
    cellfun(@(x) parainfluenza_velocity(x), ...
    parainfluenzaCombined.set2.postPath, 'uni', 0);

%% Behavior by frame

%% Functions 

function coordsByFrame = parainfluenza_position(filePath)
    positionCSV = readtable(fullfile(filePath, 'mouse_centers.xlsx'));
    positionString = positionCSV.Var2(2:end);
    positionString = cellfun(@(x) regexprep(x, '[()]', ''), positionString, 'uni', 0);
    positionCell = cellfun(@(x) str2num(x), positionString, 'uni', 0);
    positionByFrame = cat(1, positionCell{:});
    missingVals = cellfun(@(x) isempty(x), positionCell);
    numFrames = numel(positionCell);
    positionX = zeros(numFrames, 1);
    positionY = zeros(numFrames, 1);
    positionX(~missingVals) = positionByFrame(:, 1);
    positionX(missingVals) = NaN;
    positionY(~missingVals) = positionByFrame(:, 2);
    positionY(missingVals) = NaN;
    xF = fillmissing(positionX, 'linear', 'SamplePoints', 1:numFrames);
    yF = fillmissing(positionY, 'linear', 'SamplePoints', 1:numFrames);
    coordsByFrame = [xF, yF];
end

function velocityByFrame = parainfluenza_velocity(filePath)
    velocityCSV = readtable(fullfile(filePath, 'mouse_velocity.xlsx'));
    velocityByFrame = velocityCSV.Var2(2:end);
end

function peripheryByFrame = parainfluenza_periphery(coords, perim)
    innerX = [perim(1); perim(1); perim(1) + perim(3); perim(1) + perim(3)];
    innerY = [perim(2); perim(2) + perim(4); perim(2) + perim(4); perim(2)];
    peripheryByFrame = ~inpolygon(coords(:, 1), coords(:, 2), innerX, innerY);
end