function DMTS_tri_delay_proportion_training(trainingSessions, delayBins)

delayProportionBySession = cellfun(@(x) arrayfun(@(y) ...
    DMTS_tri_trial_proportion_by_delay(y, delayBins), x, 'uni', 0), ...
    trainingSessions, 'uni', 0);

delayProportionCells = arrayfun(@(x) ...
    cellfun(@(y) cellfun(@(z) z(:, x), y), delayProportionBySession, ...
    'uni', 0), 1:numel(delayBins), 'uni', 0);
delayProportionAligned = cellfun(@(x) ...
    align_training_data(trainingSessions, x), ...
    delayProportionCells, 'uni', 0);
delayProportionEras = cellfun(@(x) ...
    DMTS_tri_results_by_era(x), ...
    delayProportionAligned, 'uni', 0);
end

function dataByDelay = data_by_delay(sessionParser, delayBins)
end